[api_keys]
ELEVENLABS_API_KEY = "sk_17590c65a9b3e92e8f15687b5e494705212c209e94c39150"
WATSONX_API_KEY = "E0z5NhfKj_WATYWW9FibuZ7sU40Srde0xrM6JoEsacp3"
IBM_WATSON_TTS_API_KEY = "ut3lGKsezNXwgZn8HtYELadoTvcS7kO0PyT0XX4I_ZqF"
IBM_PROJECT_ID = "7c64d830-4d30-4727-979e-37c20bb0e8e8"
IBM_WATSON_TTS_URL = "https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/385d5247-f666-41fb-a7c0-62c9a76a2102"
